markdown: kramdown

title: "TensorBase"
description: "A modern bigdata base for massive realtime data intelligence"
keywords:
- bigdata
- massive
- database
- realtime
- intelligence
- SQL
- query
- compiler
- performance
- analytics
- warehouse
- database
- OLAP
- AP
- rust
- jit
- engineering
- modern
- high-performance
- data-analysis
- data-warehouse
- rust-lang
- scale-up
- scale-out 
- data-infrastructure

highlighter: rouge
baseurl:
xxxpermalink: /:categories/:title.html
xxxexclude: ["vendor"]
exclude: ["img-ppt"]
collections:
  thisweek:
    output: true
    permalink: /thisweek/:path/